CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	NickName VARCHAR(50) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Password VARBINARY(64) NOT NULL,
	IsAdmin BIT DEFAULT(0), 
    [Salt] VARCHAR(100) NOT NULL
)
